version: '3.8'
services:
  php:
    build:
      args:
        user: hesham
        uid: 1000
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80
    environment:
      - "DB_HOST=mysql"
      - "DB_DATABASE=GoLyvTask"
      - "DB_USERNAME=GoLyvTask"
      - "DB_PASSWORD=GoLyvTask"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    volumes:
      - .:/var/www/html
    networks:
      - service-network

  mysql:
    image: mysql:5.7.40
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=GoLyvTask"
      - "MYSQL_DATABASE=GoLyvTask"
      - "MYSQL_USER=GoLyvTask"
      - "MYSQL_PASSWORD=GoLyvTask"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3308:3306"
    networks:
      - service-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8008:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    networks:
      - service-network

  redis:
    image: redis:4.0-alpine
    command: redis-server --appendonly yes
    ports:
      - "6370:6379"
    networks:
      - service-network

volumes:
  mysqldata:

networks:
  service-network:
    driver: bridge

